version: 2
updates:
  # Enable version updates for Python dependencies managed by uv
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 5
    reviewers:
      - "qthequartermasterman"
    assignees:
      - "qthequartermasterman"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    # Group minor and patch updates together to reduce PR volume
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 3
    reviewers:
      - "qthequartermasterman"
    assignees:
      - "qthequartermasterman"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
