repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      # TODO: Re-enable when pyrefly has better numpy/pandas type support
      # - id: pyrefly
      #   name: pyrefly type checking
      #   entry: uv run pyrefly check
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   always_run: true

      - id: pytest
        name: pytest
        entry: uv run pytest -x
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
